build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u $CI_DOCKER_USERNAME -p $CI_DOCKER_PASSWORD
    - docker build -t savood/email-worker .
    - docker push savood/email-worker
  only:
    - master